{% set name = "radon" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1ac0053943a893878940fedc8b19ace70386fc9c9bf0a09229a44125ebf45b5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37]
  entry_points:
    - radon = radon:main

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
    - poetry-core
  run:
    - python
    - mando >=0.6,<0.8
    - colorama >=0.4.1
  run_constrained:
    - tomli >=2.0.1

test:
  imports:
    - radon
    - radon.cli
    - radon.cli.colors
    - radon.cli.harvest
    - radon.cli.tools
    - radon.complexity
    - radon.contrib.flake8
    - radon.metrics
    - radon.raw
    - radon.visitors
  requires:
    - pip
    - pytest >5.0
    - pytest-mock
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs radon.tests
    - radon --help

about:
  home: https://github.com/rubik/radon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Code Metrics in Python
  description: |
    Radon is a Python tool that computes various metrics from the source code. Radon can compute:

    - McCabe’s complexity, i.e. cyclomatic complexity
    - raw metrics (these include SLOC, comment lines, blank lines, &c.)
    - Halstead metrics (all of them)
    - Maintainability Index (the one used in Visual Studio)
  doc_url: https://radon.readthedocs.io
  dev_url: https://github.com/rubik/radon

extra:
  recipe-maintainers:
    - igortg
    - tonybaloney