travis:
  secure:
    BINSTAR_TOKEN: qsknduLIslBz0GS7N3v4nmrWI9DWFad3kxLlNoR88Qu64+slMlm2LAb+/uMNY9uBnlOX3che/XEirg2yUv2In05+e9/bcLc0uvSSdwBXSljOhpr/mcCI6RTFmkt3+bfqHGTCX1E19Aq94h24svCaDavyvH1mm6dNU3gw4ApleVXJtJ8Kb/duIpMzpyAyPmllIz41JnuRVqz1jYgdIZ4R0KRgkbFJ3cndBVh3Pj3I7Jees7/guszT4mlxjnlGtnKMWSMYao0L0B272LU0Cz84yAJYk+C5LghvKGAgiJJufzgFPdzwsW0AZZTPJnJ2rFE17aSOpAXobQV2k0GEGa2B4bLSyV9RfZM37eoVRNdCnuIqSpX6Kf5fBKKaFs3l0Ak30IJ5TrfsCHGPn2O/3CWDG7SV+DGV/XsJcvLjpTNFqk5SvJv33nIjAX913p+6V3z43CoHXe67njZbIHzk3qhDQrT2JiSlI7ewMuMBC8/F6Wnhsg+ihbsrZmNN5AK3TWLtAPIdI4txHSOrrxQ4EcRFxxvziXySSUAj/KOubBQ0cgjEhD8IY3jLJwAwBddvmZ4zxx78zr06SQiI36Y1ABvZUnQtcB9gQL5biyTNFHPgCbs+KZSBt5IFvXqwu1OJrlCoxuUsnFfjfPrZYBR2tPqrhqtsuyUwpq09+WApHjMW6T8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
