travis:
  secure:
    BINSTAR_TOKEN: dhyXv/MaOTyr0t2ZyHIB0Iwj++iTWylq4grDkKCksM/EJymyc/S7NMU6CFVDNUF+SrHHBnUKUH2b4dyYuSSkb+t++mjKWa9QUAlq4IXeyWvCErdjG2nyEOSf/tQCHB/cvFhj7i5+xXdVkYJVuVJmyB0E+xVrlp2K3RxEEPp3ZQvUXZusJ8PQSC9a+Qsl9IymSfTbhMvIHUX3z1fpob4fz8hh0JnS4cr0oLPJM/xylPbXRhBsupEZpZsNruvOtQIsXQ9m6Ung5kpPFmZ0Z3p06YzryXsfn8SJniu2996kBFp7b8fQvd8ob1jz+M2dwkawv07Bo+L4RnW6jAnoBw+yi8qqMPNJWxjpZvf8HYQ0gulNgeUAfYEzEzNTgd9hrGzVzbqrFgm6ZmoAWG5dPyL4F5rqkO3pp2ijOaQyulq0eIV5Lkgsg7EEEvb4wKlKZgAZlMfIwabId73s/rKDGBgSL0mMNEFCWcTeTTr6sprngSKEHZ6SW72Sn/u3NO2oqr1Hzndevi2+iktG8TdHOEYV11VhEcaKeQbTHMXAAW/4swhUE5sP8qHgVhaWstUqri1I29ovylJb63MXyTYYrE3JsZeWUk53jpopz9YU/LM/oBdzO3r3Hxkyyw2lMAHDROzM0KMV2m7JLEegmmKGxV7pDWRgXilnCdVnDb1D4ftC+/0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
